### ISSUE TITLE
wcwidth-cmd.c の FreeBSD 対応

### ISSUE THREAD

**Issue by ribbon26** [fumiyas/wcwidth-cjk#9]
wcwidth-cmd.c の13行目に #include <wchar.h>がありますが、これを10行目、 #include <alloca.h>のあとに移動していただけないでしょうか。FreeBSDでは、 wchar.h をインクルードすると、wcwidth()はライブラリではなく、マクロを呼び出してしまいますので。
https://osdn.jp/projects/mutt-j/wiki/FreeBSD%E3%81%AEwcwidth

**Comment by fumiyas** [comment]
FreeBSD ではマクロでない関数の `wcwidth`(3) は存在しないようなので、対応不可。(で正しい?)
